// LIBA Lingener Baumaschinen — alle 30 Maschinen
'use strict';

module.exports = [

  /* ─── SELBSTFAHRER (7) ─────────────────────────────────────────── */

  {
    slug: 'gm-6-asr',
    name: 'GM 6 ASR',
    category: 'Selbstfahrer',
    condition: 'Neu',
    year: null,
    subtitleDE: 'Grabenfräse für schweren Boden',
    subtitleEN: 'Trench Cutter for Heavy Ground',
    specs: [
      { de: 'Fräsbreite',        en: 'Cutting width',      val: '120–600 mm' },
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '1.700 mm' },
      { de: 'Motor',             en: 'Engine',             val: 'Perkins 6-Zyl. Turbodiesel, 168 kW / 228 PS', valEN: 'Perkins 6-cyl. turbodiesel, 168 kW / 228 hp' },
      { de: 'Fahrantrieb',       en: 'Drive',              val: 'Hydraulischer Raupenantrieb', valEN: 'Hydraulic crawler drive' },
      { de: 'Fahrgeschw.',       en: 'Travel speed',       val: '0–8 km/h' },
      { de: 'Elektrische Anlage',en: 'Electrical system',  val: '24 V' },
      { de: 'Gewicht',           en: 'Weight',             val: '17.000 kg' },
      { de: 'Länge',             en: 'Length',             val: '9.100 mm' },
      { de: 'Breite',            en: 'Width',              val: '2.500 mm' },
      { de: 'Höhe',              en: 'Height',             val: '3.100 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gm-6-asr.jpg',
    heroAltDE: 'LIBA GM 6 ASR Grabenfräse für schweren Boden',
    heroAltEN: 'LIBA GM 6 ASR trench cutter for heavy ground',
    oldUrl: 'https://lingener-baumaschinen.de/grabenfraese-fuer-schweren-boden-gm-6-asr/',
  },

  {
    slug: 'gm-4-allrad',
    name: 'GM 4 Allrad',
    nameEN: 'GM 4 All-Wheel',
    category: 'Selbstfahrer',
    condition: 'Neu',
    year: null,
    subtitleDE: 'Grabenfräse zur Sportplatzentwässerung',
    subtitleEN: 'Trench Cutter for Sports Field Drainage',
    specs: [
      { de: 'Fräsbreite',        en: 'Cutting width',      val: '70–450 mm' },
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '1.500 mm' },
      { de: 'Motor',             en: 'Engine',             val: 'Doosan Diesel, 57 kW / 77 PS', valEN: 'Doosan diesel, 57 kW / 77 hp' },
      { de: 'Fahrantrieb',       en: 'Drive',              val: 'Allradantrieb (4× Radialkolbenmotor)', valEN: 'All-wheel drive (4× radial piston motor)' },
      { de: 'Fahrgeschw.',       en: 'Travel speed',       val: '0–12 km/h' },
      { de: 'Reifenfahrwerk',    en: 'Wheel undercarriage',val: '31×15.5-12 Terra/Farmer' },
      { de: 'Gewicht',           en: 'Weight',             val: '4.400 kg' },
      { de: 'Länge',             en: 'Length',             val: '5.800 mm' },
      { de: 'Breite',            en: 'Width',              val: '1.900 mm' },
      { de: 'Höhe',              en: 'Height',             val: '2.700 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gm-4-allrad.jpg',
    heroAltDE: 'LIBA GM 4 Allrad Grabenfräse',
    heroAltEN: 'LIBA GM 4 All-Wheel trench cutter',
    oldUrl: 'https://lingener-baumaschinen.de/grabenfraese-gm4-4wd-zur-sportplatzentwaesserung/',
  },

  {
    slug: 'gm-1800-p',
    name: 'GM 1800 P',
    category: 'Selbstfahrer',
    condition: 'Neu',
    year: null,
    subtitleDE: 'Grabenfräse für Drainagearbeiten im Landschaftsbau',
    subtitleEN: 'Trench Cutter for Drainage in Landscaping',
    specs: [
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '1.800 mm' },
      { de: 'Drainrohr Ø',       en: 'Drain pipe Ø',       val: '50–160 mm' },
      { de: 'Motor',             en: 'Engine',             val: 'Deutz TCD 2015, 294 kW / 400 PS', valEN: 'Deutz TCD 2015, 294 kW / 400 hp' },
      { de: 'Fahrantrieb',       en: 'Drive',              val: 'Hydrostatischer Raupenantrieb', valEN: 'Hydrostatic crawler drive' },
      { de: 'Fahrgeschw.',       en: 'Travel speed',       val: '0–6 km/h' },
      { de: 'Fahrgestell',       en: 'Undercarriage',      val: '2.700 mm (erw. bis 4.000 mm)', valEN: '2,700 mm (ext. to 4,000 mm)' },
      { de: 'Gewicht',           en: 'Weight',             val: '30.000 kg' },
      { de: 'Länge',             en: 'Length',             val: '10.260 mm' },
      { de: 'Breite',            en: 'Width',              val: '2.982 mm' },
      { de: 'Höhe',              en: 'Height',             val: '3.446 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gm-1800-p.jpg',
    heroAltDE: 'LIBA GM 1800 P Grabenfräse für Drainage',
    heroAltEN: 'LIBA GM 1800 P trench cutter for drainage',
    oldUrl: 'https://lingener-baumaschinen.de/landschaftsbau-mit-dem-gm-1800-p/',
  },

  {
    slug: 'gm-4-raupe',
    name: 'GM 4 Raupe',
    nameEN: 'GM 4 Crawler',
    category: 'Selbstfahrer',
    condition: 'Neu',
    year: null,
    subtitleDE: 'Grabenfräse zur Glasfaserverlegung',
    subtitleEN: 'Trench Cutter for Fibre Optic Installation',
    specs: [
      { de: 'Fräsbreite',        en: 'Cutting width',      val: '70–450 mm' },
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '1.500 mm' },
      { de: 'Motor',             en: 'Engine',             val: 'Doosan Diesel, 57 kW / 77 PS', valEN: 'Doosan diesel, 57 kW / 77 hp' },
      { de: 'Fahrantrieb',       en: 'Drive',              val: 'Hydraulischer Raupenantrieb', valEN: 'Hydraulic crawler drive' },
      { de: 'Fahrgeschw.',       en: 'Travel speed',       val: '0–8 km/h' },
      { de: 'Bodenplatten',      en: 'Track shoes',        val: '300 mm gummiert', valEN: '300 mm rubber-padded' },
      { de: 'Gewicht',           en: 'Weight',             val: '4.900 kg' },
      { de: 'Länge',             en: 'Length',             val: '5.800 mm' },
      { de: 'Breite',            en: 'Width',              val: '1.900 mm' },
      { de: 'Höhe',              en: 'Height',             val: '2.700 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gm-4-raupe.jpg',
    heroAltDE: 'LIBA GM 4 Raupe Grabenfräse',
    heroAltEN: 'LIBA GM 4 Crawler trench cutter',
    oldUrl: 'https://lingener-baumaschinen.de/grabenfraese-gm-4-raupe-zur-glasfaserverlegung/',
  },

  {
    slug: 'gm-6-asr-2015',
    name: 'GM 6 ASR',
    category: 'Selbstfahrer',
    condition: 'Gebraucht',
    year: 2015,
    operatingHours: '370 Bh',
    subtitleDE: 'Grabenfräse für schweren Boden — Baujahr 2015',
    subtitleEN: 'Trench Cutter for Heavy Ground — Year 2015',
    specs: [
      { de: 'Fräsbreite',        en: 'Cutting width',      val: '120–600 mm' },
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '1.700 mm' },
      { de: 'Motor',             en: 'Engine',             val: 'Perkins 6-Zyl. Turbodiesel, 168 kW / 228 PS', valEN: 'Perkins 6-cyl. turbodiesel, 168 kW / 228 hp' },
      { de: 'Betriebsstunden',   en: 'Operating hours',    val: '370 Bh' },
      { de: 'Kettenbestückung',  en: 'Chain tooling',      val: '600 mm Meißelkette', valEN: '600 mm chisel chain' },
      { de: 'Gewicht',           en: 'Weight',             val: '17.000 kg' },
      { de: 'Länge',             en: 'Length',             val: '9.100 mm' },
      { de: 'Breite',            en: 'Width',              val: '2.500 mm' },
      { de: 'Höhe',              en: 'Height',             val: '3.100 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gm-6-asr-gebraucht.jpg',
    heroAltDE: 'LIBA GM 6 ASR Gebrauchtmaschine 2015',
    heroAltEN: 'LIBA GM 6 ASR used machine 2015',
    oldUrl: 'https://lingener-baumaschinen.de/produkt/gm-4-raupe-vorfuehrmaschine-kopie-2/',
  },

  {
    slug: 'gm-4-raupe-2023',
    name: 'GM 4 Raupe',
    nameEN: 'GM 4 Crawler',
    category: 'Selbstfahrer',
    condition: 'Vorführmaschine',
    year: 2023,
    subtitleDE: 'Grabenfräse — Vorführmaschine Baujahr 2023',
    subtitleEN: 'Trench Cutter — Demo Machine 2023',
    specs: [
      { de: 'Fräsbreite',        en: 'Cutting width',      val: '70–450 mm' },
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '1.500 mm' },
      { de: 'Motor',             en: 'Engine',             val: 'Doosan Diesel, 57 kW / 77 PS', valEN: 'Doosan diesel, 57 kW / 77 hp' },
      { de: 'Kettenbestückung',  en: 'Chain tooling',      val: '300 mm Meißelkette', valEN: '300 mm chisel chain' },
      { de: 'Gewicht',           en: 'Weight',             val: '4.900 kg' },
      { de: 'Länge',             en: 'Length',             val: '5.800 mm' },
      { de: 'Breite',            en: 'Width',              val: '1.900 mm' },
      { de: 'Höhe',              en: 'Height',             val: '2.700 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gm-4-raupe-2023.jpg',
    heroAltDE: 'LIBA GM 4 Raupe Vorführmaschine 2023',
    heroAltEN: 'LIBA GM 4 Crawler demo machine 2023',
    oldUrl: 'https://lingener-baumaschinen.de/produkt/gm-4-raupe-vorfuehrmaschine-kopie/',
  },

  {
    slug: 'gm-4-rad-2024',
    name: 'GM 4 Rad',
    nameEN: 'GM 4 Wheeled',
    category: 'Selbstfahrer',
    condition: 'Vorführmaschine',
    year: 2024,
    subtitleDE: 'Selbstfahrer-Grabenfräse — Vorführmaschine Baujahr 2024',
    subtitleEN: 'Self-Propelled Trench Cutter — Demo Machine 2024',
    specs: [
      { de: 'Fräsbreite',        en: 'Cutting width',      val: '70–450 mm' },
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '1.500 mm' },
      { de: 'Motor',             en: 'Engine',             val: 'Doosan Diesel, 57 kW / 77 PS', valEN: 'Doosan diesel, 57 kW / 77 hp' },
      { de: 'Fahrantrieb',       en: 'Drive',              val: 'Allradantrieb (4× Radialkolbenmotor)', valEN: 'All-wheel drive (4× radial piston motor)' },
      { de: 'Fahrgeschw.',       en: 'Travel speed',       val: '0–12 km/h' },
      { de: 'Reifenfahrwerk',    en: 'Wheel undercarriage',val: '31×15.5-12 Terra/Farmer' },
      { de: 'Gewicht',           en: 'Weight',             val: '4.400 kg' },
      { de: 'Länge',             en: 'Length',             val: '5.800 mm' },
      { de: 'Breite',            en: 'Width',              val: '1.900 mm' },
      { de: 'Höhe',              en: 'Height',             val: '2.700 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gm-4-rad-2024.jpg',
    heroAltDE: 'LIBA GM 4 Rad Vorführmaschine 2024',
    heroAltEN: 'LIBA GM 4 Wheel demo machine 2024',
    oldUrl: 'https://lingener-baumaschinen.de/produkt/gm-160-as-kopie/',
  },

  /* ─── SCHLEPPERANBAU (18) ──────────────────────────────────────── */

  {
    slug: 'gm-250-h',
    name: 'GM 250 H',
    category: 'Schlepperanbau',
    condition: 'Neu',
    year: null,
    subtitleDE: 'Tiefenfräse für den Tiefbau',
    subtitleEN: 'Deep-Cut Machine for Civil Engineering',
    specs: [
      { de: 'Fräsbreite',        en: 'Cutting width',      val: '70–450 mm' },
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '2.500 mm' },
      { de: 'Leistungsbedarf',   en: 'Power requirement',  val: 'ab 300 PS', valEN: 'from 300 hp' },
      { de: 'Antrieb',           en: 'Drive',              val: 'Hydraulischer Raupenantrieb', valEN: 'Hydraulic crawler drive' },
      { de: 'Fahrgeschw.',       en: 'Travel speed',       val: '0–6 km/h' },
      { de: 'Gewicht',           en: 'Weight',             val: '6.000 kg' },
      { de: 'Länge',             en: 'Length',             val: '2.500 mm' },
      { de: 'Breite',            en: 'Width',              val: '2.400 mm' },
      { de: 'Höhe',              en: 'Height',             val: '3.000 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gm-250-h.jpg',
    heroAltDE: 'LIBA GM 250 H Tiefenfräse',
    heroAltEN: 'LIBA GM 250 H deep-cut machine',
    oldUrl: 'https://lingener-baumaschinen.de/tiefenfraese-gm-250-h-fuer-tiefbau/',
  },

  {
    slug: 'gm-180-af',
    name: 'GM 180 AF',
    category: 'Schlepperanbau',
    condition: 'Neu',
    year: null,
    subtitleDE: 'Hochleistungs-Grabenfräse zur Kabelverlegung',
    subtitleEN: 'High-Performance Trench Cutter for Cable Installation',
    specs: [
      { de: 'Fräsbreite',        en: 'Cutting width',      val: '200–600 mm' },
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '1.800 mm' },
      { de: 'Leistungsbedarf',   en: 'Power requirement',  val: 'ab 300 PS / 10 t Trägergerät', valEN: 'from 300 hp / 10 t carrier' },
      { de: 'Antrieb',           en: 'Drive',              val: 'Zapfwelle (mechanisch)', valEN: 'PTO shaft (mechanical)' },
      { de: 'Ölvolumenstrom',    en: 'Oil flow rate',      val: '60 L/min' },
      { de: 'Druck',             en: 'Pressure',           val: '180 bar' },
      { de: 'Gewicht',           en: 'Weight',             val: '5.000 kg' },
      { de: 'Länge',             en: 'Length',             val: '5.000 mm' },
      { de: 'Breite',            en: 'Width',              val: '2.400 mm' },
      { de: 'Höhe',              en: 'Height',             val: '2.000 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gm-180-af-m.jpg',
    heroAltDE: 'LIBA GM 180 AF Schlepperanbau-Grabenfräse',
    heroAltEN: 'LIBA GM 180 AF tractor-mounted trench cutter',
    oldUrl: 'https://lingener-baumaschinen.de/kabelverlegung-mit-der-gm-180-af/',
  },

  {
    slug: 'gm-600-r',
    name: 'Fräsrad GM 600 R',
    nameEN: 'GM 600 R Cutter Wheel',
    category: 'Schlepperanbau',
    condition: 'Neu',
    year: null,
    subtitleDE: 'Fräsrad für Kabel- und Leitungsbau',
    subtitleEN: 'Milling Wheel for Cable and Pipeline Construction',
    specs: [
      { de: 'Fräsbreite',        en: 'Cutting width',      val: '80–200 mm' },
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '600 mm' },
      { de: 'Leistungsbedarf',   en: 'Power requirement',  val: 'ab 190 PS', valEN: 'from 190 hp' },
      { de: 'Ölvolumenstrom',    en: 'Oil flow rate',      val: '100 L/min' },
      { de: 'Druck',             en: 'Pressure',           val: '200 bar' },
      { de: 'Anbau',             en: 'Attachment',         val: 'Dreipunktaufnahme', valEN: 'Three-point linkage' },
      { de: 'Gewicht',           en: 'Weight',             val: '2.000 kg' },
      { de: 'Länge',             en: 'Length',             val: '4.000 mm' },
      { de: 'Breite',            en: 'Width',              val: '2.400 mm' },
      { de: 'Höhe',              en: 'Height',             val: '1.800 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gm-600-r-m.jpg',
    heroAltDE: 'LIBA Fräsrad GM 600 R',
    heroAltEN: 'LIBA milling wheel GM 600 R',
    oldUrl: 'https://lingener-baumaschinen.de/kabelbau-mit-der-gm-600-r/',
  },

  {
    slug: 'gm-160-as',
    name: 'GM 160 AS',
    category: 'Schlepperanbau',
    condition: 'Neu',
    year: null,
    subtitleDE: 'Anbaufräse für Drainage',
    subtitleEN: 'Attachment Cutter for Drainage',
    specs: [
      { de: 'Fräsbreite',        en: 'Cutting width',      val: '150–450 mm' },
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '1.600 mm' },
      { de: 'Trägergerät',       en: 'Carrier machine',    val: 'Schlepper/Unimog ab 160 PS (Hydrostat)', valEN: 'Tractor/Unimog from 160 hp (hydrostatic)' },
      { de: 'Antrieb',           en: 'Drive',              val: 'Zapfwelle (1.000 U/min) oder Hydraulikmotor', valEN: 'PTO shaft (1,000 rpm) or hydraulic motor' },
      { de: 'Standardausstattung', en: 'Standard equipment', val: '2 Schnecken', valEN: '2 augers' },
      { de: 'Gewicht',           en: 'Weight',             val: '2.300 kg' },
      { de: 'Länge',             en: 'Length',             val: '4.100 mm' },
      { de: 'Breite',            en: 'Width',              val: '1.800 mm' },
      { de: 'Höhe',              en: 'Height',             val: '2.000 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gm-160-as.jpg',
    heroAltDE: 'LIBA GM 160 AS Anbaufräse für Drainage',
    heroAltEN: 'LIBA GM 160 AS attachment cutter for drainage',
    oldUrl: 'https://lingener-baumaschinen.de/grabenfraese-gm-160-as-fuer-drainage/',
  },

  {
    slug: 'gm-140-af',
    name: 'GM 140 AF',
    category: 'Schlepperanbau',
    condition: 'Neu',
    year: null,
    subtitleDE: 'Leistungsstarke Bodenfräse für den Schlepper',
    subtitleEN: 'High-Performance Soil Cutter for Tractors',
    specs: [
      { de: 'Fräsbreite',        en: 'Cutting width',      val: '70–450 mm' },
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '1.500 mm' },
      { de: 'Trägergerät',       en: 'Carrier machine',    val: 'Schlepper/Unimog ab 70 PS (Hydrostat)', valEN: 'Tractor/Unimog from 70 hp (hydrostatic)' },
      { de: 'Antrieb',           en: 'Drive',              val: 'Zapfwelle (1.000 U/min)', valEN: 'PTO shaft (1,000 rpm)' },
      { de: 'Gewicht',           en: 'Weight',             val: '1.800 kg' },
      { de: 'Länge',             en: 'Length',             val: '3.700 mm' },
      { de: 'Breite',            en: 'Width',              val: '1.900 mm' },
      { de: 'Höhe',              en: 'Height',             val: '1.800 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gm-140-af.jpg',
    heroAltDE: 'LIBA GM 140 AF Bodenfräse',
    heroAltEN: 'LIBA GM 140 AF soil cutter',
    oldUrl: 'https://lingener-baumaschinen.de/bodenfraese-140-af/',
  },

  {
    slug: 'gm-1-af',
    name: 'GM 1 AF',
    category: 'Schlepperanbau',
    condition: 'Neu',
    year: null,
    subtitleDE: 'Kompakte Anbaufräse für Drainage & Kabelbau',
    subtitleEN: 'Compact Attachment Cutter for Drainage & Cable Installation',
    specs: [
      { de: 'Fräsbreite',        en: 'Cutting width',      val: '70–300 mm' },
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '1.200 mm' },
      { de: 'Trägergerät',       en: 'Carrier machine',    val: 'Schlepper/Unimog ab 60 PS (Hydrostat)', valEN: 'Tractor/Unimog from 60 hp (hydrostatic)' },
      { de: 'Antrieb',           en: 'Drive',              val: 'Zapfwelle (540 oder 1.000 U/min)', valEN: 'PTO shaft (540 or 1,000 rpm)' },
      { de: 'Gewicht',           en: 'Weight',             val: '1.000 kg' },
      { de: 'Länge',             en: 'Length',             val: '3.100 mm' },
      { de: 'Breite',            en: 'Width',              val: '1.600 mm' },
      { de: 'Höhe',              en: 'Height',             val: '1.500 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gm-1-af.jpg',
    heroAltDE: 'LIBA GM 1 AF Traktorfräse',
    heroAltEN: 'LIBA GM 1 AF tractor cutter',
    oldUrl: 'https://lingener-baumaschinen.de/traktorfraese-gm-1-as/',
  },

  {
    slug: 'gm-300-h',
    name: 'GM 300 H',
    category: 'Schlepperanbau',
    condition: 'Neu',
    year: null,
    subtitleDE: 'Tiefenfräse für Kabelverlegung',
    subtitleEN: 'Deep-Cut Machine for Cable Installation',
    specs: [
      { de: 'Fräsbreite',        en: 'Cutting width',      val: '150–400 mm' },
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '3.000 mm' },
      { de: 'Leistungsbedarf',   en: 'Power requirement',  val: 'ab 250 PS', valEN: 'from 250 hp' },
      { de: 'Gewicht',           en: 'Weight',             val: '8.000 kg' },
      { de: 'Länge',             en: 'Length',             val: '3.000 mm' },
      { de: 'Breite',            en: 'Width',              val: '2.600 mm' },
      { de: 'Höhe',              en: 'Height',             val: '3.500 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gm-300-h.jpg',
    heroAltDE: 'LIBA GM 300 H Tiefenfräse',
    heroAltEN: 'LIBA GM 300 H deep-cut machine',
    oldUrl: 'https://lingener-baumaschinen.de/tiefenfraese-die-optimale-loesung-fuer-effizientes-fraesen/',
  },

  {
    slug: 'gm-140-af-600-h',
    name: 'GM 140 AF 600 H',
    category: 'Schlepperanbau',
    condition: 'Neu',
    year: null,
    subtitleDE: 'Revolutionäre Anbaufräse mit flexiblem Powerkit',
    subtitleEN: 'Innovative Attachment Cutter with Flexible Power Kit',
    specs: [
      { de: 'Fräsbreite (1 Balken)', en: 'Cutting width (1 bar)', val: '120–400 mm' },
      { de: 'Fräsbreite (2 Balken)', en: 'Cutting width (2 bars)', val: '500–600 mm' },
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '1.500 mm' },
      { de: 'Trägergerät',       en: 'Carrier machine',    val: 'Schlepper ab 10 t', valEN: 'Tractor from 10 t' },
      { de: 'Antrieb',           en: 'Drive',              val: 'Zapfwelle (mechanisch)', valEN: 'PTO shaft (mechanical)' },
      { de: 'Gewicht',           en: 'Weight',             val: '3.500 kg' },
      { de: 'Länge',             en: 'Length',             val: '3.400 mm' },
      { de: 'Breite',            en: 'Width',              val: '1.900 mm' },
      { de: 'Höhe',              en: 'Height',             val: '1.800 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gm-140-af-600-h.webp',
    heroAltDE: 'LIBA GM 140 AF 600 H Anbaufräse',
    heroAltEN: 'LIBA GM 140 AF 600 H attachment cutter',
    oldUrl: 'https://lingener-baumaschinen.de/grabenfraese-gm-140-afh-600-h/',
  },

  {
    slug: 'gm-1-as',
    name: 'GM 1 AS',
    category: 'Schlepperanbau',
    condition: 'Neu',
    year: null,
    subtitleDE: 'Anbaufräse für schnelle Erdkabelverlegung',
    subtitleEN: 'Attachment Cutter for Fast Earth Cable Installation',
    specs: [
      { de: 'Fräsbreite',        en: 'Cutting width',      val: '70–300 mm' },
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '1.200 mm' },
      { de: 'Trägergerät',       en: 'Carrier machine',    val: 'Schlepper/Unimog ab 60 PS (Hydrostat)', valEN: 'Tractor/Unimog from 60 hp (hydrostatic)' },
      { de: 'Antrieb',           en: 'Drive',              val: 'Zapfwelle (540 U/min)', valEN: 'PTO shaft (540 rpm)' },
      { de: 'Gewicht',           en: 'Weight',             val: '800 kg' },
      { de: 'Länge',             en: 'Length',             val: '3.100 mm' },
      { de: 'Breite',            en: 'Width',              val: '1.600 mm' },
      { de: 'Höhe',              en: 'Height',             val: '1.500 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gm-1-as.jpg',
    heroAltDE: 'LIBA GM 1 AS Anbaufräse',
    heroAltEN: 'LIBA GM 1 AS attachment cutter',
    oldUrl: 'https://lingener-baumaschinen.de/erdkabel-verlegen-mit-der-gm-1-as/',
  },

  {
    slug: 'gm-160-af',
    name: 'GM 160 AF',
    category: 'Schlepperanbau',
    condition: 'Neu',
    year: null,
    subtitleDE: 'Grabenfräse für Unimog — flexibel und präzise',
    subtitleEN: 'Trench Cutter for Unimog — Flexible and Precise',
    specs: [
      { de: 'Fräsbreite',        en: 'Cutting width',      val: '150–450 mm' },
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '1.600 mm' },
      { de: 'Trägergerät',       en: 'Carrier machine',    val: 'Schlepper/Unimog ab 160 PS (Hydrostat)', valEN: 'Tractor/Unimog from 160 hp (hydrostatic)' },
      { de: 'Antrieb',           en: 'Drive',              val: 'Zapfwelle (1.000 U/min) oder Hydraulikmotor', valEN: 'PTO shaft (1,000 rpm) or hydraulic motor' },
      { de: 'Gewicht',           en: 'Weight',             val: '2.300 kg' },
      { de: 'Länge',             en: 'Length',             val: '4.400 mm' },
      { de: 'Breite',            en: 'Width',              val: '1.800 mm' },
      { de: 'Höhe',              en: 'Height',             val: '2.000 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gm-160-af-m.jpg',
    heroAltDE: 'LIBA GM 160 AF Unimog-Grabenfräse',
    heroAltEN: 'LIBA GM 160 AF Unimog trench cutter',
    oldUrl: 'https://lingener-baumaschinen.de/grabenfraese-gm-160-af-eine-grabenfraese-fuer-unimog/',
  },

  {
    slug: 'gm-450-h',
    name: 'GM 450 H',
    category: 'Schlepperanbau',
    condition: 'Neu',
    year: null,
    subtitleDE: 'Tiefenfräse für anspruchsvollste Tiefbauarbeiten',
    subtitleEN: 'Deep-Cut Machine for the Most Demanding Civil Engineering',
    specs: [
      { de: 'Fräsbreite',        en: 'Cutting width',      val: '200–450 mm' },
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '4.500 mm' },
      { de: 'Leistungsbedarf',   en: 'Power requirement',  val: 'ab 400 PS', valEN: 'from 400 hp' },
      { de: 'Antrieb',           en: 'Drive',              val: 'Hydraulisch über Zapfwelle', valEN: 'Hydraulic via PTO shaft' },
      { de: 'Fahrgeschw.',       en: 'Travel speed',       val: '0–6 km/h' },
      { de: 'Gewicht',           en: 'Weight',             val: '11.000 kg' },
      { de: 'Länge',             en: 'Length',             val: '5.000 mm' },
      { de: 'Breite',            en: 'Width',              val: '2.500 mm' },
      { de: 'Höhe',              en: 'Height',             val: '3.100 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gm-450-h.jpg',
    heroAltDE: 'LIBA GM 450 H Tiefenfräse',
    heroAltEN: 'LIBA GM 450 H deep-cut machine',
    oldUrl: 'https://lingener-baumaschinen.de/grabenfraese-gm-450-h/',
  },

  {
    slug: 'gmv-100',
    name: 'GMV 100',
    category: 'Schlepperanbau',
    condition: 'Neu',
    year: null,
    subtitleDE: 'Anbaupflug für Schlepper oder Bagger',
    subtitleEN: 'Attachment Plough for Tractors or Excavators',
    specs: [
      { de: 'Schwertbreite',     en: 'Blade width',        val: '50 mm' },
      { de: 'Verlegetiefe max.', en: 'Max. installation depth', val: '800 mm' },
      { de: 'Antrieb',           en: 'Drive',              val: 'Hydraulisch', valEN: 'Hydraulic' },
      { de: 'Ölvolumenstrom',    en: 'Oil flow rate',      val: '100 L/min' },
      { de: 'Druck',             en: 'Pressure',           val: '200–250 bar' },
      { de: 'Gewicht',           en: 'Weight',             val: '1.200 kg' },
      { de: 'Länge',             en: 'Length',             val: '2.200 mm' },
      { de: 'Breite',            en: 'Width',              val: '1.200 mm' },
      { de: 'Höhe',              en: 'Height',             val: '2.100 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gmv-100.jpg',
    heroAltDE: 'LIBA GMV 100 Anbaupflug',
    heroAltEN: 'LIBA GMV 100 attachment plough',
    oldUrl: 'https://lingener-baumaschinen.de/anbaupflug-gmv-100/',
  },

  {
    slug: 'gm-300-hf',
    name: 'GM 300 HF',
    category: 'Schlepperanbau',
    condition: 'Neu',
    year: null,
    subtitleDE: 'Tiefenfräse für effiziente Tieffräsarbeiten',
    subtitleEN: 'Deep-Cut Machine for Efficient Deep Milling',
    specs: [
      { de: 'Fräsbreite',        en: 'Cutting width',      val: '150–600 mm' },
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '2.000 mm' },
      { de: 'Motor',             en: 'Engine',             val: '6-Zyl.-Turbodiesel, 195 PS', valEN: '6-cyl. turbodiesel, 195 hp' },
      { de: 'Antrieb',           en: 'Drive',              val: 'Hydraulisch über Zapfwelle', valEN: 'Hydraulic via PTO shaft' },
      { de: 'Gewicht',           en: 'Weight',             val: '10.000 kg' },
      { de: 'Länge',             en: 'Length',             val: '3.000 mm' },
      { de: 'Breite',            en: 'Width',              val: '2.500 mm' },
      { de: 'Höhe',              en: 'Height',             val: '3.100 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gm-300-hf.jpg',
    heroAltDE: 'LIBA GM 300 HF Tiefenfräse',
    heroAltEN: 'LIBA GM 300 HF deep-cut machine',
    oldUrl: 'https://lingener-baumaschinen.de/tiefe-fraesarbeiten-mit-der-gm-300-hf/',
  },

  {
    slug: 'gmv-130',
    name: 'GMV 130',
    category: 'Schlepperanbau',
    condition: 'Neu',
    year: null,
    subtitleDE: 'Vibrationskabelpflug für präzises Verlegen',
    subtitleEN: 'Vibrating Cable Plough for Precise Installation',
    specs: [
      { de: 'Schwertbreite max.', en: 'Max. blade width',  val: '80 mm' },
      { de: 'Verlegetiefe max.', en: 'Max. installation depth', val: '1.300 mm' },
      { de: 'Trägergerät',       en: 'Carrier machine',    val: 'Dreipunkt-Schlepper oder Bagger 20 t (Superkriechgang)', valEN: 'Three-point tractor or 20 t excavator (super-creep gear)' },
      { de: 'Gewicht',           en: 'Weight',             val: '2.400 kg' },
      { de: 'Länge',             en: 'Length',             val: '3.500 mm' },
      { de: 'Breite',            en: 'Width',              val: '1.800 mm' },
      { de: 'Höhe',              en: 'Height',             val: '2.700 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gmv-130.jpg',
    heroAltDE: 'LIBA GMV 130 Vibrationskabelpflug',
    heroAltEN: 'LIBA GMV 130 vibrating cable plough',
    oldUrl: 'https://lingener-baumaschinen.de/vibrationskabelpflug-gmv-130/',
  },

  {
    slug: 'unimogfraese',
    name: 'Unimogfräse',
    nameEN: 'Unimog cutter',
    category: 'Schlepperanbau',
    condition: 'Neu',
    year: null,
    subtitleDE: 'Vielseitige Anbaufräse für Unimog-Fahrzeuge',
    subtitleEN: 'Versatile Attachment Cutter for Unimog Vehicles',
    specs: [
      { de: 'Fräsbreite',        en: 'Cutting width',      val: '150–400 mm' },
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '1.600 mm' },
      { de: 'Trägergerät',       en: 'Carrier machine',    val: 'Mercedes-Benz Unimog ab 160 PS', valEN: 'Mercedes-Benz Unimog from 160 hp' },
      { de: 'Antrieb',           en: 'Drive',              val: 'Zapfwelle / Hydraulik', valEN: 'PTO shaft / hydraulic' },
    ],
    heroImage: '/assets/images/products/maschinen/unimogfraese.jpg',
    heroAltDE: 'LIBA Unimogfräse',
    heroAltEN: 'LIBA Unimog cutter',
    oldUrl: 'https://lingener-baumaschinen.de/unimogfraese/',
  },

  {
    slug: 'gmv-130-2020',
    name: 'GMV 130',
    category: 'Schlepperanbau',
    condition: 'Gebraucht',
    year: 2020,
    subtitleDE: 'Kabelpflug — Gebrauchtmaschine Baujahr 2020',
    subtitleEN: 'Cable Plough — Used Machine Year 2020',
    specs: [
      { de: 'Schwertbreite',     en: 'Blade width',        val: '70 mm' },
      { de: 'Verlegetiefe max.', en: 'Max. installation depth', val: '1.300 mm' },
      { de: 'Trägergerät',       en: 'Carrier machine',    val: 'Dreipunkt-Schlepper oder Bagger 20 t', valEN: 'Three-point tractor or 20 t excavator' },
      { de: 'Gewicht',           en: 'Weight',             val: '2.400 kg' },
      { de: 'Länge',             en: 'Length',             val: '3.500 mm' },
      { de: 'Breite',            en: 'Width',              val: '1.800 mm' },
      { de: 'Höhe',              en: 'Height',             val: '2.700 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gmv-130-gebraucht.jpg',
    heroAltDE: 'LIBA GMV 130 Gebrauchtmaschine',
    heroAltEN: 'LIBA GMV 130 used machine',
    oldUrl: 'https://lingener-baumaschinen.de/produkt/gebrauchter-pflug-gmv-130/',
  },

  {
    slug: 'gm-140-af-2011',
    name: 'GM 140 AF',
    category: 'Schlepperanbau',
    condition: 'Gebraucht',
    year: 2011,
    subtitleDE: 'Traktorfräse — Gebrauchtmaschine Baujahr 2011',
    subtitleEN: 'Tractor Cutter — Used Machine Year 2011',
    specs: [
      { de: 'Fräsbreite',        en: 'Cutting width',      val: '70–450 mm' },
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '1.500 mm' },
      { de: 'Trägergerät',       en: 'Carrier machine',    val: 'Schlepper/Unimog ab 70 PS (Hydrostat)', valEN: 'Tractor/Unimog from 70 hp (hydrostatic)' },
      { de: 'Antrieb',           en: 'Drive',              val: 'Zapfwelle (1.000 U/min)', valEN: 'PTO shaft (1,000 rpm)' },
      { de: 'Gewicht',           en: 'Weight',             val: '1.800 kg' },
      { de: 'Länge',             en: 'Length',             val: '3.700 mm' },
      { de: 'Breite',            en: 'Width',              val: '1.900 mm' },
      { de: 'Höhe',              en: 'Height',             val: '1.800 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gm-140-af-gebraucht.jpg',
    heroAltDE: 'LIBA GM 140 AF Gebrauchtmaschine',
    heroAltEN: 'LIBA GM 140 AF used machine',
    oldUrl: 'https://lingener-baumaschinen.de/produkt/gm-140-h-vorfuehrmaschine-kopie/',
  },

  {
    slug: 'gm-160-as-2014',
    name: 'GM 160 AS',
    category: 'Schlepperanbau',
    condition: 'Gebraucht',
    year: 2014,
    subtitleDE: 'Grabenfräse — Gebrauchtmaschine Baujahr 2014',
    subtitleEN: 'Trench Cutter — Used Machine Year 2014',
    specs: [
      { de: 'Fräsbreite',        en: 'Cutting width',      val: '150–450 mm' },
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '1.600 mm' },
      { de: 'Trägergerät',       en: 'Carrier machine',    val: 'Schlepper/Unimog ab 160 PS (Hydrostat)', valEN: 'Tractor/Unimog from 160 hp (hydrostatic)' },
      { de: 'Antrieb',           en: 'Drive',              val: 'Zapfwelle (mechanisch)', valEN: 'PTO shaft (mechanical)' },
      { de: 'Kettenbestückung',  en: 'Chain tooling',      val: '300 mm Messer', valEN: '300 mm blades' },
      { de: 'Gewicht',           en: 'Weight',             val: '2.300 kg' },
      { de: 'Länge',             en: 'Length',             val: '4.100 mm' },
      { de: 'Breite',            en: 'Width',              val: '1.800 mm' },
      { de: 'Höhe',              en: 'Height',             val: '2.000 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gm-160-as-gebraucht.jpg',
    heroAltDE: 'LIBA GM 160 AS Gebrauchtmaschine',
    heroAltEN: 'LIBA GM 160 AS used machine',
    oldUrl: 'https://lingener-baumaschinen.de/produkt/gm-160-as/',
  },

  /* ─── BAGGERANBAU (5) ──────────────────────────────────────────── */

  {
    slug: 'gm-140-afh-500',
    name: 'GM 140 AFH-500',
    category: 'Baggeranbau',
    condition: 'Neu',
    year: null,
    subtitleDE: 'Baggerfräse für Rohrleitungsbau, Kabelverlegung und Drainage',
    subtitleEN: 'Excavator Cutter for Pipeline, Cable Installation and Drainage',
    specs: [
      { de: 'Fräsbreite',        en: 'Cutting width',      val: '70–450 mm' },
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '1.500 mm' },
      { de: 'Trägergerät',       en: 'Carrier machine',    val: 'Hydraulikbagger ab 15 t', valEN: 'Hydraulic excavator from 15 t' },
      { de: 'Ölvolumenstrom',    en: 'Oil flow rate',      val: '120–140 L/min' },
      { de: 'Druck',             en: 'Pressure',           val: '250–300 bar' },
      { de: 'Antrieb',           en: 'Drive',              val: 'Hydraulisch über Radialkolbenmotor', valEN: 'Hydraulic via radial piston motor' },
      { de: 'Gewicht',           en: 'Weight',             val: '1.800 kg' },
      { de: 'Länge',             en: 'Length',             val: '3.400 mm' },
      { de: 'Breite',            en: 'Width',              val: '1.500 mm' },
      { de: 'Höhe',              en: 'Height',             val: '1.800 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gm-140-afh-500-m.jpg',
    heroAltDE: 'LIBA GM 140 AFH-500 Baggerfräse',
    heroAltEN: 'LIBA GM 140 AFH-500 excavator cutter',
    oldUrl: 'https://lingener-baumaschinen.de/baggerfrase-gm-140-afh-500/',
  },

  {
    slug: 'gm-140-afh-600',
    name: 'GM 140 AFH-600',
    category: 'Baggeranbau',
    condition: 'Neu',
    year: null,
    subtitleDE: 'Leistungsstarke Grabenfräse für Rohrleitungsbau',
    subtitleEN: 'High-Performance Trench Cutter for Pipeline Construction',
    specs: [
      { de: 'Fräsbreite',        en: 'Cutting width',      val: '120–600 mm' },
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '1.500 mm' },
      { de: 'Trägergerät',       en: 'Carrier machine',    val: 'Hydraulikbagger ab 17 t', valEN: 'Hydraulic excavator from 17 t' },
      { de: 'Ölvolumenstrom',    en: 'Oil flow rate',      val: '120–140 L/min' },
      { de: 'Druck',             en: 'Pressure',           val: '300–350 bar' },
      { de: 'Antrieb',           en: 'Drive',              val: 'Hydraulisch über Radialkolbenmotor', valEN: 'Hydraulic via radial piston motor' },
      { de: 'Gewicht',           en: 'Weight',             val: '3.500 kg' },
      { de: 'Länge',             en: 'Length',             val: '3.400 mm' },
      { de: 'Breite',            en: 'Width',              val: '1.900 mm' },
      { de: 'Höhe',              en: 'Height',             val: '1.800 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gm-140-afh-600.jpg',
    heroAltDE: 'LIBA GM 140 AFH-600 Baggerfräse',
    heroAltEN: 'LIBA GM 140 AFH-600 excavator cutter',
    oldUrl: 'https://lingener-baumaschinen.de/rohrleitungsbau-mit-der-gm-140-afh-600/',
  },

  {
    slug: 'gm-140-h',
    name: 'GM 140 H',
    category: 'Baggeranbau',
    condition: 'Neu',
    year: null,
    subtitleDE: 'Baggeranbaufräse für Glasfaser, Drainage und Rohrleitungsbau',
    subtitleEN: 'Excavator-Mounted Cutter for Fibre Optic, Drainage and Pipelines',
    specs: [
      { de: 'Fräsbreite',        en: 'Cutting width',      val: '125–600 mm' },
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '1.500 mm' },
      { de: 'Trägergerät',       en: 'Carrier machine',    val: 'Hydraulikbagger ab 17 t', valEN: 'Hydraulic excavator from 17 t' },
      { de: 'Ölvolumenstrom',    en: 'Oil flow rate',      val: '160–250 L/min' },
      { de: 'Druck',             en: 'Pressure',           val: '250–350 bar' },
      { de: 'Antrieb',           en: 'Drive',              val: 'Hydraulisch über Radialkolbenmotor', valEN: 'Hydraulic via radial piston motor' },
      { de: 'Standardausstattung', en: 'Standard equipment', val: '2 Schnecken', valEN: '2 augers' },
      { de: 'Gewicht',           en: 'Weight',             val: '2.800 kg' },
      { de: 'Länge',             en: 'Length',             val: '3.000 mm' },
      { de: 'Breite',            en: 'Width',              val: '1.500 mm' },
      { de: 'Höhe',              en: 'Height',             val: '1.400 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gm-140-h.jpg',
    heroAltDE: 'LIBA GM 140 H Baggeranbaufräse',
    heroAltEN: 'LIBA GM 140 H excavator-mounted cutter',
    oldUrl: 'https://lingener-baumaschinen.de/baggeranbaufraese-gm-140-h/',
  },

  {
    slug: 'gm-140-afh-500-2011',
    name: 'GM 140 AFH 500',
    category: 'Baggeranbau',
    condition: 'Gebraucht',
    year: 2011,
    subtitleDE: 'Baggerfräse — Gebrauchtmaschine Baujahr 2011',
    subtitleEN: 'Excavator Cutter — Used Machine Year 2011',
    specs: [
      { de: 'Fräsbreite',        en: 'Cutting width',      val: '70–450 mm' },
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '1.500 mm' },
      { de: 'Trägergerät',       en: 'Carrier machine',    val: 'Hydraulikbagger ab 15 t', valEN: 'Hydraulic excavator from 15 t' },
      { de: 'Ölvolumenstrom',    en: 'Oil flow rate',      val: '120–140 L/min' },
      { de: 'Druck',             en: 'Pressure',           val: '250–300 bar' },
      { de: 'Gewicht',           en: 'Weight',             val: '1.800 kg' },
      { de: 'Länge',             en: 'Length',             val: '3.400 mm' },
      { de: 'Breite',            en: 'Width',              val: '1.500 mm' },
      { de: 'Höhe',              en: 'Height',             val: '1.800 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gm-140-afh-500-gebraucht.jpg',
    heroAltDE: 'LIBA GM 140 AFH 500 Gebrauchtmaschine',
    heroAltEN: 'LIBA GM 140 AFH 500 used machine',
    oldUrl: 'https://lingener-baumaschinen.de/produkt/gm-140-h-vorfuehrmaschine-kopie-2/',
  },

  {
    slug: 'gm-140-h-2009',
    name: 'GM 140 H',
    category: 'Baggeranbau',
    condition: 'Vorführmaschine',
    year: 2009,
    subtitleDE: 'Baggeranbaufräse — Vorführmaschine Baujahr 2009',
    subtitleEN: 'Excavator-Mounted Cutter — Demo Machine Year 2009',
    specs: [
      { de: 'Fräsbreite',        en: 'Cutting width',      val: '125–600 mm' },
      { de: 'Frästiefe max.',    en: 'Max. cutting depth', val: '1.500 mm' },
      { de: 'Trägergerät',       en: 'Carrier machine',    val: 'Hydraulikbagger ab 17 t', valEN: 'Hydraulic excavator from 17 t' },
      { de: 'Ölvolumenstrom',    en: 'Oil flow rate',      val: '160–250 L/min' },
      { de: 'Druck',             en: 'Pressure',           val: '250–350 bar' },
      { de: 'Gewicht',           en: 'Weight',             val: '2.800 kg' },
      { de: 'Länge',             en: 'Length',             val: '3.000 mm' },
      { de: 'Breite',            en: 'Width',              val: '1.500 mm' },
      { de: 'Höhe',              en: 'Height',             val: '1.400 mm' },
    ],
    heroImage: '/assets/images/products/maschinen/gm-140-h-gebraucht.jpg',
    heroAltDE: 'LIBA GM 140 H Vorführmaschine',
    heroAltEN: 'LIBA GM 140 H demo machine',
    oldUrl: 'https://lingener-baumaschinen.de/produkt/gm-140-h-vorfuehrmaschine/',
  },

];
